version: '1.0.0'
services:
  jenkins:
    # Container 이름
    container_name: jenkins
    # image 이름
    image: jenkins/jenkins:jdk11
    # volume 할당
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock ubuntu/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - TZ=Asia/Seoul
    user: root
    networks:
      - pipeline_network
      - import_cicd_network

  nexus:
    # container name
    container_name: nexus
    # image name
    image: klo2k/nexus3
    volumes:
      - ./nexus/nexus-data:/nexus-data
    environment:
      - TZ=Asia/Seoul
    ports:
      - "5050:5050"
      - "8081:8081"
    user: root
    networks:
      - pipeline_network
      - import_cicd_network
    

networks:
  # pipeline 전용 private network
  pipeline_network:
    driver: bridge
  import_cicd_network:
    driver: bridge
    external:
      true